import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cac-q2-plto-ui-app-01.azurewebsites.net/');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('qatest20250815101@plooto-admin-test.ca');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('oET5g^nme@%2rzS!DEF@trW!');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByText('QA Assignment 20250815 Client').first().click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.getByRole('link', { name: 'Payables' }).click();
  await page.getByRole('link', { name: 'Receivables' }).click();
  await page.getByRole('link', { name: 'Contacts' }).click();
  await page.getByRole('link', { name: 'Accounts' }).click();
  await page.getByRole('link', { name: 'Approvals' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Help Center' }).click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'QA Assignment 20250815 Client' }).click();
  await page.getByRole('menuitem', { name: 'Switch Company' }).click();
  await page.getByText('QA Assignment 20250815 Client').nth(2).click();
  await page.getByRole('button', { name: 'QA Assignment 20250815 Client' }).click();
  await page.getByRole('menuitem', { name: 'My Profile' }).click();
  await page.getByRole('button', { name: 'QA Assignment 20250815 Client' }).click();
  await page.getByRole('menuitem', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'QA Assignment 20250815 Client' }).click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('link', { name: 'User Management' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByRole('textbox', { name: 'First name' }).click();
  await page.getByRole('textbox', { name: 'First name' }).fill('test');
  await page.getByRole('textbox', { name: 'First name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last name' }).fill('user');
  await page.getByRole('textbox', { name: 'Last name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('oET5g^nme@%2rzS!DEF@trW!');
  await page.getByRole('combobox', { name: 'Role Viewer' }).click();
  await page.getByRole('option', { name: 'CFO' }).click();
  await page.getByRole('checkbox', { name: 'Add/edit users' }).check();
  await page.getByRole('checkbox', { name: 'Edit company details and' }).check();
  await page.getByRole('checkbox', { name: 'Connect/disconnect external' }).check();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).fill('putter-thanes-3t@icloud.com');
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('link', { name: 'Single Sign-On' }).click();
  await page.getByRole('link', { name: 'Controls' }).click();
  await page.getByRole('link', { name: 'Billing & Subscriptions' }).click();
  await page.getByRole('link', { name: 'Capture Settings' }).click();
  await page.getByRole('link', { name: 'Accounting Software' }).click();
  await page.getByRole('link', { name: 'Payment Preferences' }).click();
});